print("Starting Installation Process of EVERYTHING needed.")
print("Starting Pine3d installation.")
shell.run("wget run https://pinestore.cc/d/2")
print("Done! Starting PineForge installtion..")
shell.run("delete Minecraft.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/Minecraft.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/PineForge.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/config.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/gui.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/input.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/inventory.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/ui.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/player.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/renderer.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/world.lua")
print("Main Game Files Downloaded! Installing mods.")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/CCMods/pineforge_base/config.txt")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/CCMods/pineforge_base/mod.lua")
shell.run("wget https://raw.githubusercontent.com/DrNightheart/PineForge-CCMinecraft-Modloader/refs/heads/main/PineForge%20Files/CCMods/examplemod.ccmod")
print("Relocating files to correct directories..")
shell.run("rename examplemod.ccmod CCMods/examplemod.ccmod")
shell.run("rename config.txt CCMods/pineforge_base/config.txt")
shell.run("rename mod.lua CCMods/pineforge_base/mod.lua")
print("deleting no-longer used files from base CCMinecraft")
shell.run("delete README.md")
term.clear()
print("Done!")

